title: Saraswathi R
logo: /assets/images/headshot_img.png
logo_width: 120 px
description: >
  Data scientist who turns raw data into smart decisions. Passionate about AI, automation, and solving real-world problems with data.<br><br>
  Always up for a challenge, a good laugh, and an opportunity to build something impactful. 
show_downloads: false
theme: jekyll-theme-minimal
