title: Saraswathi R
logo: /assets/images/headshot_img.png
logo_width: 120 px
description: >
  Data scientist who turns raw data into smart decisions. Passionate about AI and automation.<br><br>
  ***Always up for a challenge, a good laugh, and an opportunity to build something impactful.***<br><br><br>

show_downloads: false
theme: jekyll-theme-minimal
